import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { FileStorageEntity } from '../entities/file-storage.entity';
import { MinioService } from './minio.service';

@Injectable()
export class StorageService {
  constructor(
    @InjectRepository(FileStorageEntity)
    private readonly fileStorageRepository: Repository<FileStorageEntity>,
    private readonly minioService: MinioService,
  ) {}

  async uploadFile(
    file: Express.Multer.File,
  ): Promise<{ id: string; path: string }> {
    // Upload to MinIO
    const objectName = await this.minioService.uploadFile(
      file.originalname,
      file.buffer,
      file.mimetype,
    );

    // Save metadata to database (id will be auto-generated by TypeORM)
    const fileStorage = this.fileStorageRepository.create({
      path: objectName,
      fileType: file.mimetype,
      fileName: file.originalname,
      size: file.size,
    });

    const savedFile = await this.fileStorageRepository.save(fileStorage);

    return {
      id: savedFile.id,
      path: savedFile.path,
    };
  }

  async getPresignedUrl(fileId: string, expiry: number = 3600): Promise<string> {
    const fileStorage = await this.fileStorageRepository.findOne({
      where: { id: fileId },
    });

    if (!fileStorage) {
      throw new Error(`File with ID ${fileId} not found`);
    }

    return await this.minioService.getPresignedUrl(fileStorage.path, expiry);
  }

  async getFileById(fileId: string): Promise<FileStorageEntity> {
    const fileStorage = await this.fileStorageRepository.findOne({
      where: { id: fileId },
    });

    if (!fileStorage) {
      throw new Error(`File with ID ${fileId} not found`);
    }

    return fileStorage;
  }
}

